defaults:
  - train_default
  - sae_trainer_cfg: standard

# Trainer cfg parameters
sae_trainer_cfg:
  activation_dim: ${datamodule.activation_dim}
  dict_size: 10240
  # steps: ${datamodule.steps}
  # decay_start: null
  layer: ${datamodule.layer_number}
  lm_name: ${datamodule.model_type} 