# Core model architecture
dict_class: "MatryoshkaBatchTopKSAE"
trainer_class: "MatryoshkaBatchTopKTrainer"
activation_dim: null  # Set in train.yaml
dict_size: null      # Set in train.yaml

# Training parameters
lr: 1e-4
warmup_steps: 1000  # Min(10000, steps//10)
steps: null          # Required
decay_start: null    # Set to steps//2 at runtime
auxk_alpha: 0.03125 # 1/32 as in Gao et al.
threshold_beta: 0.999 # Default in `dictionary_learning/trainers/matryoshka_batch_top_k.py`
threshold_start_step: 1000 # Default in `dictionary_learning/trainers/matryoshka_batch_top_k.py`
# top_k_aux: 1

# Model configuration
seed: 0
device: "cuda"
layer: null         # Required
lm_name: null      # Required
k: 100               # Number of features to keep per batch

# Group configuration
group_fractions: [0.0273, 0.0427, 0.0759, 0.1708, 0.6833]  # Required, fractions that sum to 1, Default is power law for N = 5, alpha = 2.0.

# Logging
wandb_name: null   # Optional
submodule_name: null  # Optional, "embed" if using embeddings