defaults:
  - base

model_type: "3b"
layer_number: 36
activation_dim: 2560

optimized_dir: ${datamodule.s3_bucket_uri}/optimized/3b_36_1_shards

toks_per_bucket: 2048
buckets_per_epoch: 112 #TODO: check